platform :ios, '8.3'
inhibit_all_warnings!

project 'MZCroppableView'
use_frameworks!

target 'MZCroppableView_Example' do
  pod 'MZCroppableView'
end

target 'MZCroppableView_Tests' do
  pod 'MZCroppableView'
  
end
